### PR TITLE
Issue release v3

### LINKED ISSUE #101: Removed/deleted properties in Firestore are not removed/deleted from the store
`Add` and `update` properties in a specific Firestore document works perfectly but when I `remove` property from the Firestore document with (Firebase console browser) it stays in the store, which is Akita BUG.

`Add` and `remove` the whole document from the collection also works perfectly as expected.

How to reproduce the bug:
1. load data in the component with the `this.data$ = this.query.selectAll()`
2. show them in the component with `data$ | async | json`
3. OPTIONAL `add` or `update` some property this should work perfectly
4. OPTIONAL `add` or `remove` some documents from the collection this should also work perfectly
5. `remove/delete` some property from some Firestore Document from Firebase Console, in Firestore browser property are removed but not from Angular app from the Akita store
6. after the Angular app `refresh/reload` Akita store is updated with the fresh data from the Firestore and deleted property/properties from the step 5. are not visible

Lib's versions in the app:
```
"dependencies": {
    "@angular/core": "~9.1.7",
    "@angular/fire": "^6.0.0-rc.1",
    "@angular/material": "^9.2.3",
    "@angular/platform-browser": "~9.1.7",
    "@angular/platform-browser-dynamic": "~9.1.7",
    "@angular/router": "~9.1.7",
    "@datorama/akita": "^4.23.2",
    "@ngneat/until-destroy": "^7.1.6",
    "akita-ng-fire": "^1.5.13",
    "firebase": "^7.8.0",
    "rxjs": "~6.5.5",
    "rxjs-compat": "^6.5.4",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.3"
  }
```

### LINKED ISSUE #111: upgrade akita-ng-fire to akita v5
When i would like to use akita-ng-fire with akita 5.0.0 i have an error 
`
ERROR in ./node_modules/akita-ng-fire/__ivy_ngcc__/fesm2015/akita-ng-fire.js 39:30-42
"export 'StoreActions' was not found in '@datorama/akita'
ERROR in ./node_modules/akita-ng-fire/__ivy_ngcc__/fesm2015/akita-ng-fire.js 47:30-42
"export 'StoreActions' was not found in '@datorama/akita'
ERROR in ./node_modules/akita-ng-fire/__ivy_ngcc__/fesm2015/akita-ng-fire.js 55:30-42
"export 'StoreActions' was not found in '@datorama/akita'
ERROR in ./node_modules/akita-ng-fire/__ivy_ngcc__/fesm2015/akita-ng-fire.js 64:30-42
"export 'StoreActions' was not found in '@datorama/akita'
ERROR in ./node_modules/akita-ng-fire/__ivy_ngcc__/fesm2015/akita-ng-fire.js 69:30-42
"export 'StoreActions' was not found in '@datorama/akita'
ERROR in ./node_modules/akita-ng-fire/__ivy_ngcc__/fesm2015/akita-ng-fire.js 77:30-42
"export 'StoreActions' was not found in '@datorama/akita'
`
@NetanelBasal told me to post an issue

### PR DESCRIPTION
**Pull request by fritzschoff**
fix #101 
fix #111

### CODE REVIEW

File: projects/akita-ng-fire/src/lib/utils/sync-from-action.ts [hunk 1]
```diff
@@ -29,8 +29,7 @@ export function removeStoreEntity(storeName: string, entityIds: string | string[
 /** Update one or several entities in the store */
 export function updateStoreEntity(storeName: string, entityIds: string | string[], data: any) {
   removeStoreEntity(storeName, entityIds);
-  runEntityStoreAction(storeName, EntityStoreAction.AddEntities, add => add(data))
-  runEntityStoreAction(storeName, EntityStoreAction.UpdateEntities, update => update(entityIds, data))
+  runEntityStoreAction(storeName, EntityStoreAction.AddEntities, add => add(data));
```
Comment (GrandSchtroumpf) [inline projects/akita-ng-fire/src/lib/utils/sync-from-action.ts:32]: You might want to run both in a transaction to avoid jump in the page.

Comment (GrandSchtroumpf) [reply projects/akita-ng-fire/src/lib/utils/sync-from-action.ts:32]: Also you if `entityIds` is  `["1", "2"]` & data `{ text: "Hello" }` using `add(data)` will not work as expected.
Check if it's possible but I think you want to do : 
```typescript
add => add(entityIds, data)
```
